apiVersion: batch/v1
kind: CronJob
metadata:
  name: busybox-cronjob1
spec:
  schedule: "0 4 * * *"   #at 04:00 every day
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox:1.28
            command:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
