secret:
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secrets
type: Opaque
data:
  ME_CONFIG_MONGODB_AUTH_DATABASE: YWRtaW4=
  ME_CONFIG_MONGODB_AUTH_USERNAME: cm9vdA==
  ME_CONFIG_MONGODB_AUTH_PASSWORD: bW9qZWhhc2xvMTIz
