apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-mongo
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/mongo
