#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: mongo-claim
#spec:
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 1Gi
#  storageClassName: standard


apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: triple-stack
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
